---
resources:
- name: newman-repo
  type: git
  source:
    uri: https://github.com/RickyCooperIBM/postman_demo.git
  
jobs:
- name: test-rest-api
  public: true
  plan:
  - get: newman-repo
  - task: test-api
    file: newman-repo/newman/newman-task.yml
    params: { "COLLECTION_URL": "https://raw.githubusercontent.com/RickyCooperIBM/postman_demo/main/newman/test-collection.json?token=AU2CCLRRKMAZI5GJXCZHGGLBHCDRQ" }