---
resources:
- name: newman-repo
  type: git
  source:
    uri: https://github.com/RickyCooperIBM/postman_demo.git
  
jobs:

- name: test-rest-api
  public: true
  plan:
  - get: newman-repo
  - task: test-api
    file: newman-repo/newman/newman-task.yml
    params: { "COLLECTION_URL": "https://raw.githubusercontent.com/RickyCooperIBM/postman_demo/main/newman/test_collection.json" }

  - task: Commit-testReport
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      - name: testReports
      run:
        path: sh
        args:
        - -cx
        - |
          ls -l .
          cat testReports/report.xml
